cmake_minimum_required(VERSION 3.29)
project(dominoes)

set(CMAKE_CXX_STANDARD 14)

include_directories(.)

add_executable(dominoes
        cmake-build-debug/dominoes-test_data/10/10-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/10/10-input.txt
        cmake-build-debug/dominoes-test_data/10/10-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/10/10-output.txt
        cmake-build-debug/dominoes-test_data/100/100-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/100/100-input.txt
        cmake-build-debug/dominoes-test_data/100/100-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/100/100-output.txt
        cmake-build-debug/dominoes-test_data/1000/1000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/1000/1000-input.txt
        cmake-build-debug/dominoes-test_data/1000/1000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/1000/1000-output.txt
        cmake-build-debug/dominoes-test_data/10000/10000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/10000/10000-input.txt
        cmake-build-debug/dominoes-test_data/10000/10000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/10000/10000-output.txt
        cmake-build-debug/dominoes-test_data/100000/100000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/100000/100000-input.txt
        cmake-build-debug/dominoes-test_data/100000/100000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/100000/100000-output.txt
        cmake-build-debug/dominoes-test_data/1000000/1000000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/1000000/1000000-input.txt
        cmake-build-debug/dominoes-test_data/1000000/1000000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/1000000/1000000-output.txt
        cmake-build-debug/dominoes-test_data/30/30-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/30/30-input.txt
        cmake-build-debug/dominoes-test_data/30/30-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/30/30-output.txt
        cmake-build-debug/dominoes-test_data/300/300-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/300/300-input.txt
        cmake-build-debug/dominoes-test_data/300/300-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/300/300-output.txt
        cmake-build-debug/dominoes-test_data/3000/3000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/3000/3000-input.txt
        cmake-build-debug/dominoes-test_data/3000/3000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/3000/3000-output.txt
        cmake-build-debug/dominoes-test_data/30000/30000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/30000/30000-input.txt
        cmake-build-debug/dominoes-test_data/30000/30000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/30000/30000-output.txt
        cmake-build-debug/dominoes-test_data/300000/300000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/300000/300000-input.txt
        cmake-build-debug/dominoes-test_data/300000/300000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/300000/300000-output.txt
        cmake-build-debug/dominoes-test_data/60/60-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/60/60-input.txt
        cmake-build-debug/dominoes-test_data/60/60-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/60/60-output.txt
        cmake-build-debug/dominoes-test_data/600/600-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/600/600-input.txt
        cmake-build-debug/dominoes-test_data/600/600-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/600/600-output.txt
        cmake-build-debug/dominoes-test_data/6000/6000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/6000/6000-input.txt
        cmake-build-debug/dominoes-test_data/6000/6000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/6000/6000-output.txt
        cmake-build-debug/dominoes-test_data/60000/60000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/60000/60000-input.txt
        cmake-build-debug/dominoes-test_data/60000/60000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/60000/60000-output.txt
        cmake-build-debug/dominoes-test_data/600000/600000-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/600000/600000-input.txt
        cmake-build-debug/dominoes-test_data/600000/600000-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/600000/600000-output.txt
        cmake-build-debug/dominoes-test_data/example/example-input-uncoloured-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/example/example-input.txt
        cmake-build-debug/dominoes-test_data/example/example-output-alternating-EXTENSION.txt
        cmake-build-debug/dominoes-test_data/example/example-output.txt
    dominolinebuilder.cpp
    dominolinebuilder.h
    main.cpp)
